# Site settings
title: Josenberg - Um pacato programador
email: mbx.philipe@gmail.com.br
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: "none"
url: "http://josenberg.com.br" # the base hostname & protocol for your site
github_username:  josenberg

# Build settings
markdown: kramdown
